<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFJNNxaD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFJNNxaD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFJNNxaD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFJNNxaD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFJNNxaD\App_KernelDevDebugContainer([
    'container.build_hash' => 'FJNNxaD',
    'container.build_id' => '280f5529',
    'container.build_time' => 1682417621,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFJNNxaD');
