<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZyzAeJN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZyzAeJN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZyzAeJN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZyzAeJN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZyzAeJN\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZyzAeJN',
    'container.build_id' => 'b5c07a2d',
    'container.build_time' => 1682412401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZyzAeJN');
